Windup-3431: Rebranding to MTR - CLI Guide
windup/windup-documentation pull request #569
Opened 2022-10-24 14:11 UTC by sbeskin-redhat

Windup-3431: Rebranding to MTR - CLI Guide
Resolves: https://issues.redhat.com/browse/WINDUP-3431
MTR 1.0

2022-11-02 21:07 UTC, sshveta approved these changes

2022-11-02 21:09 UTC, sshveta requested changes

2022-11-02 21:09 UTC, sshveta commented on docs/topics/templates/document-attributes.adoc
>  :MTADownloadPageURL: https://developers.redhat.com/products/mta/download
This URL needs to be updated.

2022-11-04 10:43 UTC, stillalearner commented on docs/topics/what-is-the-toolkit.adoc
>  For more information about use cases and migration paths, see the link:https://developers.redhat.com/products/mta/use-cases[MTA for developers] web page.
Replace MTA with MTR

2022-11-04 10:45 UTC, stillalearner commented on docs/topics/add-rule-to-mta.adoc
>  [id="add-rule-to-mta_{context}"]
mta to mtr

2022-11-04 10:46 UTC, stillalearner commented on docs/topics/exclude-files-and-packages.adoc
>  * `~/.mta/ignore/`
mta to mtr

2022-11-04 10:46 UTC, stillalearner commented on docs/topics/installing-intellij-idea-plugin.adoc
> +* The latest version of `windup-cli` from the link:{MTADownloadPageURL}[{ProductShortName} download page]
MTA to MTR

2022-11-04 10:46 UTC, stillalearner commented on docs/topics/installing-web-console-on-openshift.adoc
>  . Navigate to the link:{MTADownloadPageURL}[{ProductShortName} Download page] and download the {WebName} `Local install & OpenShift` file.
MTA to MTR

2022-11-07 16:51 UTC, stillalearner commented on docs/topics/cli-run.adoc
> +. Execute the `windup-cli` script, or `windup-cli.bat` for Windows, and specify the appropriate arguments:
mtr-cli

2022-11-07 16:51 UTC, stillalearner commented on docs/topics/cli-run.adoc
> +$ ./windup-cli --input /path/to/jee-example-app-1.0.0.ear \
mtr-cli

2022-11-16 15:09 UTC, sshveta requested changes

2022-11-16 15:09 UTC, sshveta commented on docs/topics/web-start.adoc
>  NOTE: In a Windows environment, use the `run_mta.bat` script.
script name is not run_mta.sh . 
It is run_windup.bat

2022-11-16 15:09 UTC, sshveta commented on docs/rules-development-guide/master.adoc
> +// MTA Rules
Replace MTA with MTR

2022-11-16 15:09 UTC, sshveta commented on docs/rules-development-guide/master.adoc
> +// Review the Existing MTA XML Rules
Replace MTA with MTR

2022-11-16 15:09 UTC, sshveta commented on docs/topics/cli-args.adoc
> +See link:{ProductDocIntroToMTAGuideURL}/index#migration_paths_getting-started-guide[Supported migration paths] in _{IntroToMTABookName}_ for the appropriate JBoss EAP version.
Replace MTA with MTR

2022-11-16 15:09 UTC, sshveta commented on docs/topics/cli-args.adoc
> +See link:{ProductDocIntroToMTAGuideURL}/index#migration_paths_getting-started-guide[Supported migration paths] in _{IntroToMTABookName}_ for the appropriate JBoss EAP version.
Replace MTA with MTR

2022-11-16 15:09 UTC, sshveta commented on docs/topics/installing-web-console-or-cli-tool.adoc
>  . Open a browser and navigate to `\http://localhost:8080/mta-web`. The {WebName} login page is displayed in your browser.
Replace MTA with MTR

2022-11-16 15:09 UTC, sshveta commented on docs/topics/vs-code-extension-run-configuration.adoc
> +* `windup-cli` executable installed. You can download the `windup-cli` executable from link:https://developers.redhat.com/products/mta/download[MTA download].
Replace MTA with MTR

2022-11-17 07:19 UTC, stillalearner commented on docs/topics/web-start.adoc
>  $ <{ProductShortName}_HOME>/run_mta.sh
run_windup.sh

2022-11-17 07:20 UTC, stillalearner commented on docs/topics/installing-web-console-or-cli-tool.adoc
> +$ <MTR_HOME>/run_mtr.sh
@sshveta it should be run_windup.sh right?

2022-11-17 07:20 UTC, stillalearner commented on docs/topics/installing-web-console-or-cli-tool.adoc
> +C:\<MTR_HOME>\run_mtr.bat
@sshveta here also, run_windup.bat  ?

2022-11-21 09:23 UTC, merged