WINDUP-3487:MTR Web Console Guide OpenShift Templates
windup/windup-documentation pull request #574
Opened 2022-11-03 12:00 UTC by sbeskin-redhat

WINDUP-3487:MTR Web Console Guide OpenShift Templates
Resolves: https://issues.redhat.com/browse/WINDUP-3487
MTR 1.1.1

2022-11-07 15:51 UTC, stillalearner commented on docs/topics/installing-web-console-on-openshift.adoc
>  . Click the `secure-mta-web-console` route to open the {WebName} in a new browser window.
mta to mtr

2022-11-07 15:52 UTC, stillalearner commented on docs/topics/installing-web-console-on-openshift.adoc
>  . In the *Topology* view, click the `mta-web-console` application and then click the *Resources* tab.
mta to mtr

2022-11-07 17:38 UTC, sshveta requested changes

2022-11-07 17:38 UTC, sshveta commented on docs/topics/installing-web-console-on-openshift.adoc
>  You can install the {WebName} on {ocp-short} 4.6 and later versions with the {ProductName} Operator.
Openshift versions to be updated from 4.9 to 4.11

2022-11-15 18:49 UTC, sshveta approved these changes

2022-11-16 19:35 UTC, merged